/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingcabapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author TARAL THAKKAR
 */
public class Confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     */
    public Confirmation(int pi,int di) {
        initComponents();
        Location l = new Location();
        int distance = l.getDistance(pi,di);
        int dur = l.tripDuration(pi,di);
        int fare = l.getfare(pi,di);
        int driverIndex = Customer.BookACab(pi);
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cabbookingapp?serverTimezone=UTC","root","preet@0431");
                ResultSet rs;
                String query = "select * from driver";
                PreparedStatement st = con.prepareStatement(query);
                rs = st.executeQuery();
                rs.next();
                for(int i=0;i<driverIndex;++i)
                    rs.next();
                jLabeld_name1.setText("Drivername : "+rs.getString("drivername"));
                jLabeld_rating.setText("Rating :"+rs.getString("rating"));
                jLabeld_t_no.setText("Vehicle ID :"+rs.getString("tno"));
                jlabeld_phno.setText("Phone Number :"+rs.getString("phno"));
                jLabeldistance.setText("Trip Distance :"+ distance+" Km");
                jLabelduration.setText("Trip Duration :"+dur+" minutes");
                jLabelfare.setText("Fare : "+fare+" Rs");
                Customer.reduceWallet(fare);
                st.close();
                con.close();
                }
            catch(ClassNotFoundException | SQLException e){
                System.out.println("Exception:"+e);
                }
    }
    
    private Confirmation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlabeld_phno = new javax.swing.JLabel();
        jLabeld_name1 = new javax.swing.JLabel();
        jLabeld_t_no = new javax.swing.JLabel();
        jLabeld_rating = new javax.swing.JLabel();
        jLabeldistance = new javax.swing.JLabel();
        jLabelfare = new javax.swing.JLabel();
        jLabelduration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlabeld_phno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabeld_phno.setText("jLabel1");

        jLabeld_name1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeld_name1.setText("jLabel1");

        jLabeld_t_no.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeld_t_no.setText("jLabel1");

        jLabeld_rating.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeld_rating.setText("jLabel1");

        jLabeldistance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabeldistance.setText("jLabel1");

        jLabelfare.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelfare.setText("jLabel1");

        jLabelduration.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelduration.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabeld_name1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jlabeld_phno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeld_t_no, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeld_rating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabeldistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelduration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelfare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabeld_name1)
                .addGap(18, 18, 18)
                .addComponent(jlabeld_phno)
                .addGap(18, 18, 18)
                .addComponent(jLabeld_t_no)
                .addGap(18, 18, 18)
                .addComponent(jLabeld_rating)
                .addGap(18, 18, 18)
                .addComponent(jLabeldistance)
                .addGap(18, 18, 18)
                .addComponent(jLabelduration)
                .addGap(18, 18, 18)
                .addComponent(jLabelfare)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabeld_name1;
    private javax.swing.JLabel jLabeld_rating;
    private javax.swing.JLabel jLabeld_t_no;
    private javax.swing.JLabel jLabeldistance;
    private javax.swing.JLabel jLabelduration;
    private javax.swing.JLabel jLabelfare;
    private javax.swing.JLabel jlabeld_phno;
    // End of variables declaration//GEN-END:variables
}
