/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookingcabapp;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Manan patel
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public Customer Customer;
    public void transC(Customer Customer)
    {
        this.Customer=Customer;
    }
    public HomePage() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_u = new javax.swing.JLabel();
        jLabel_closewindow = new javax.swing.JLabel();
        jLabel_minimizewindow = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_EditProf = new javax.swing.JButton();
        jButton2_mywallet = new javax.swing.JButton();
        jButton_logout = new javax.swing.JButton();
        jButton_bookcab = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));

        jLabel_u.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel_u.setText("jlabel");

        jLabel_closewindow.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_closewindow.setText("X");
        jLabel_closewindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_closewindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closewindowMouseClicked(evt);
            }
        });

        jLabel_minimizewindow.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel_minimizewindow.setText("_");
        jLabel_minimizewindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimizewindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizewindowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jLabel_u, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel_minimizewindow)
                .addGap(18, 18, 18)
                .addComponent(jLabel_closewindow)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_minimizewindow)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_closewindow)
                    .addComponent(jLabel_u, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton_EditProf.setBackground(new java.awt.Color(255, 255, 0));
        jButton_EditProf.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_EditProf.setText("Edit Profile");
        jButton_EditProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_EditProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_EditProfMouseClicked(evt);
            }
        });

        jButton2_mywallet.setBackground(new java.awt.Color(255, 255, 0));
        jButton2_mywallet.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2_mywallet.setText("My Wallet");
        jButton2_mywallet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2_mywallet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2_mywalletMouseClicked(evt);
            }
        });

        jButton_logout.setBackground(new java.awt.Color(255, 255, 0));
        jButton_logout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_logout.setText("Logout");
        jButton_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_logoutMouseClicked(evt);
            }
        });

        jButton_bookcab.setBackground(new java.awt.Color(255, 255, 0));
        jButton_bookcab.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton_bookcab.setText("Book A Cab");
        jButton_bookcab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_bookcab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_bookcabMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_bookcabMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton_bookcab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2_mywallet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_EditProf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jButton_bookcab)
                .addGap(49, 49, 49)
                .addComponent(jButton_EditProf)
                .addGap(49, 49, 49)
                .addComponent(jButton2_mywallet)
                .addGap(50, 50, 50)
                .addComponent(jButton_logout)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closewindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closewindowMouseClicked
       Customer.changeLoginStatus(0);
       this.dispose();
    }//GEN-LAST:event_jLabel_closewindowMouseClicked

    private void jLabel_minimizewindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizewindowMouseClicked
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizewindowMouseClicked

    private void jButton_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_logoutMouseClicked
        LoginPage mp = new LoginPage();
        mp.setVisible(true);
        mp.pack();
        mp.setLocationRelativeTo(null);
        mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Customer.changeLoginStatus(0);
        this.dispose();
    }//GEN-LAST:event_jButton_logoutMouseClicked

    private void jButton_bookcabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_bookcabMouseEntered

    }//GEN-LAST:event_jButton_bookcabMouseEntered

    private void jButton_bookcabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_bookcabMouseClicked
        if( Customer.getWallet() < 300 ){
            JOptionPane.showMessageDialog(null,"Insufficient wallet balance.\nMinimum Rs. 300 required.");
        }
        else{
            BookCabWindow mp = new BookCabWindow();
            mp.setVisible(true);
            mp.pack();
            mp.setLocationRelativeTo(null);
            mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            mp.transC(Customer);
            this.dispose();
        }
    }//GEN-LAST:event_jButton_bookcabMouseClicked

    private void jButton2_mywalletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2_mywalletMouseClicked
            MyWallet mw = new MyWallet();
            mw.setVisible(true);
            mw.pack();
            mw.setLocationRelativeTo(null);
            mw.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            int wallet = Customer.getWallet();
            mw.jLabel3_wallet.setText(wallet+"");
            mw.transC(Customer);
            this.dispose();
    }//GEN-LAST:event_jButton2_mywalletMouseClicked

    private void jButton_EditProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_EditProfMouseClicked
            EditProfile mw = new EditProfile();
            mw.setVisible(true);
            mw.pack();
            mw.setLocationRelativeTo(null);
            mw.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            mw.jTextField_uname.setText(Customer.getUsername());
            mw.jTextField_email.setText(Customer.getEmail());
            mw.jTextField_phno.setText(Customer.getPhone());
            mw.jTextField_passwd.setText(Customer.getPassword());
            mw.transC(Customer);
            this.dispose();
    }//GEN-LAST:event_jButton_EditProfMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2_mywallet;
    private javax.swing.JButton jButton_EditProf;
    private javax.swing.JButton jButton_bookcab;
    private javax.swing.JButton jButton_logout;
    private javax.swing.JLabel jLabel_closewindow;
    private javax.swing.JLabel jLabel_minimizewindow;
    public javax.swing.JLabel jLabel_u;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
